server:
  port: 9044

## 设置openFeign和sleuth的日志级别为debug，方便查看日志信息
logging:
  level:
    root: debug

spring:
  application:
    ## 指定服务名称，在nacos中的名字
    name: skywalking-alarm
  cloud:
    nacos:
      ## 注册中心配置
      discovery:
        # nacos的服务地址，nacos-server中IP地址:端口号
        server-addr: 192.168.10.105:8848


