logging:
  level:
    org.springframework.cloud.sleuth: DEBUG
    reactor.netty.http.client: DEBUG

server:
  port: 9032
spring:
  application:
    ## 指定服务名称，在nacos中的名字
    name: sleuth-product
  cloud:
    nacos:
      ## 注册中心配置
      discovery:
        # nacos的服务地址，nacos-server中IP地址:端口号
        server-addr: 192.168.10.105:8848
  sleuth:
    sampler:
      # 日志数据采样百分比，默认0.1(10%)，这里为了测试设置成了100%，生产环境只需要0.1即可
      probability: 1.0
  zipkin:
      #zipkin server的请求地址，集成MQ之后，这个配置将不需要
      #    base-url: http://192.168.1.150:9411
      #让nacos把它当成一个URL，而不要当做服务名
    discovery-client-enabled: false
      # 数据传输模式，默认web（Http形式），还可以配置消息中间件，支持RabbitMQ，Kafka，ActiveMQ
    sender:
      type: rabbit

    ## rabbitMQ相关的配置
  rabbitmq:
    addresses: 192.168.10.105
    username: admin
    password: root1003
